# Generated by Django 4.1.7 on 2023-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
