# Generated by Django 4.1.7 on 2023-06-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_model', '0002_order_address_order_city_order_email_order_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastName',
        ),
    ]
